package com.xwtech.mss.pub.po;



/**
 * MssFrameFieldCheck generated by MyEclipse - Hibernate Tools
 */

public class FrameFieldCheck  implements java.io.Serializable {


    // Fields    

     private Long fieldCheckId;
     private String tableName;
     private String fieldName;
     private String checkValue;
     private String checkDesc;
     private String constantName;
     private String checkState;


    // Constructors

    /** default constructor */
    public FrameFieldCheck() {
    }

	/** minimal constructor */
    public FrameFieldCheck(Long fieldCheckId, String checkValue, String checkDesc, String constantName, String checkState) {
        this.fieldCheckId = fieldCheckId;
        this.checkValue = checkValue;
        this.checkDesc = checkDesc;
        this.constantName = constantName;
        this.checkState = checkState;
    }
    
    /** full constructor */
    public FrameFieldCheck(Long fieldCheckId, String tableName, String fieldName, String checkValue, String checkDesc, String constantName, String checkState) {
        this.fieldCheckId = fieldCheckId;
        this.tableName = tableName;
        this.fieldName = fieldName;
        this.checkValue = checkValue;
        this.checkDesc = checkDesc;
        this.constantName = constantName;
        this.checkState = checkState;
    }

   
    // Property accessors

    public Long getFieldCheckId() {
        return this.fieldCheckId;
    }
    
    public void setFieldCheckId(Long fieldCheckId) {
        this.fieldCheckId = fieldCheckId;
    }

    public String getTableName() {
        return this.tableName;
    }
    
    public void setTableName(String tableName) {
        this.tableName = tableName;
    }

    public String getFieldName() {
        return this.fieldName;
    }
    
    public void setFieldName(String fieldName) {
        this.fieldName = fieldName;
    }

    public String getCheckValue() {
        return this.checkValue;
    }
    
    public void setCheckValue(String checkValue) {
        this.checkValue = checkValue;
    }

    public String getCheckDesc() {
        return this.checkDesc;
    }
    
    public void setCheckDesc(String checkDesc) {
        this.checkDesc = checkDesc;
    }

    public String getConstantName() {
        return this.constantName;
    }
    
    public void setConstantName(String constantName) {
        this.constantName = constantName;
    }

    public String getCheckState() {
        return this.checkState;
    }
    
    public void setCheckState(String checkState) {
        this.checkState = checkState;
    }
   








}