package com.xwtech.mss.pub.po;



/**
 * MssFrameLoginLog generated by MyEclipse - Hibernate Tools
 */

public class FrameLoginLog  implements java.io.Serializable {


    // Fields    

     private Long loginLogId;
     private String loginIp;
     private String loginName;
     private String loginPwd;
     private String loginTime;
     private String loginResultCode;
     private String logoutTime;


    // Constructors

    /** default constructor */
    public FrameLoginLog() {
    }

	/** minimal constructor */
    public FrameLoginLog(Long loginLogId, String loginIp, String loginTime, String loginResultCode) {
        this.loginLogId = loginLogId;
        this.loginIp = loginIp;
        this.loginTime = loginTime;
        this.loginResultCode = loginResultCode;
    }
    
    /** full constructor */
    public FrameLoginLog(Long loginLogId, String loginIp, String loginName, String loginPwd, String loginTime, String loginResultCode, String logoutTime) {
        this.loginLogId = loginLogId;
        this.loginIp = loginIp;
        this.loginName = loginName;
        this.loginPwd = loginPwd;
        this.loginTime = loginTime;
        this.loginResultCode = loginResultCode;
        this.logoutTime = logoutTime;
    }

   
    // Property accessors

    public Long getLoginLogId() {
        return this.loginLogId;
    }
    
    public void setLoginLogId(Long loginLogId) {
        this.loginLogId = loginLogId;
    }

    public String getLoginIp() {
        return this.loginIp;
    }
    
    public void setLoginIp(String loginIp) {
        this.loginIp = loginIp;
    }

    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public String getLoginPwd() {
        return this.loginPwd;
    }
    
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd;
    }

    public String getLoginTime() {
        return this.loginTime;
    }
    
    public void setLoginTime(String loginTime) {
        this.loginTime = loginTime;
    }

    public String getLoginResultCode() {
        return this.loginResultCode;
    }
    
    public void setLoginResultCode(String loginResultCode) {
        this.loginResultCode = loginResultCode;
    }

    public String getLogoutTime() {
        return this.logoutTime;
    }
    
    public void setLogoutTime(String logoutTime) {
        this.logoutTime = logoutTime;
    }
   








}