package com.xwtech.mss.pub.po;



/**
 * MssFrameUrl generated by MyEclipse - Hibernate Tools
 */

public class FrameUrl  implements java.io.Serializable {


    // Fields    

     private Long urlId;
     private Role role;
     private String urlValue;
     private String urlName;
     private String urlDesc;
     private String urlState;


    // Constructors

    /** default constructor */
    public FrameUrl() {
    }

	/** minimal constructor */
    public FrameUrl(Long urlId, String urlValue, String urlName, String urlState) {
        this.urlId = urlId;
        this.urlValue = urlValue;
        this.urlName = urlName;
        this.urlState = urlState;
    }
    
    /** full constructor */
    public FrameUrl(Long urlId, Role role, String urlValue, String urlName, String urlDesc, String urlState) {
        this.urlId = urlId;
        this.role = role;
        this.urlValue = urlValue;
        this.urlName = urlName;
        this.urlDesc = urlDesc;
        this.urlState = urlState;
    }

   
    // Property accessors

    public Long getUrlId() {
        return this.urlId;
    }
    
    public void setUrlId(Long urlId) {
        this.urlId = urlId;
    }

    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }

    public String getUrlValue() {
        return this.urlValue;
    }
    
    public void setUrlValue(String urlValue) {
        this.urlValue = urlValue;
    }

    public String getUrlName() {
        return this.urlName;
    }
    
    public void setUrlName(String urlName) {
        this.urlName = urlName;
    }

    public String getUrlDesc() {
        return this.urlDesc;
    }
    
    public void setUrlDesc(String urlDesc) {
        this.urlDesc = urlDesc;
    }

    public String getUrlState() {
        return this.urlState;
    }
    
    public void setUrlState(String urlState) {
        this.urlState = urlState;
    }
   








}