package com.xwtech.mss.pub.po;



/**
 * FrameOrgCityRelation generated by MyEclipse - Hibernate Tools
 */

public class FrameOrgCityRelation  implements java.io.Serializable {


    // Fields    

     private Long relationId;
     private Orgnization orgnization;
     private String cityId;


    // Constructors

    /** default constructor */
    public FrameOrgCityRelation() {
    }

    
    /** full constructor */
    public FrameOrgCityRelation(Orgnization orgnization, String cityId) {
        this.orgnization = orgnization;
        this.cityId = cityId;
    }

   
    // Property accessors

    public Long getRelationId() {
        return this.relationId;
    }
    
    public void setRelationId(Long relationId) {
        this.relationId = relationId;
    }

    public Orgnization getOrgnization() {
        return this.orgnization;
    }
    
    public void setOrgnization(Orgnization orgnization) {
        this.orgnization = orgnization;
    }

    public String getCityId() {
        return this.cityId;
    }
    
    public void setCityId(String cityId) {
        this.cityId = cityId;
    }
   








}