package com.xwtech.mss.pub.po;

import java.util.HashSet;
import java.util.Set;


/**
 * MssMenu generated by MyEclipse - Hibernate Tools
 */

public class Menu  implements java.io.Serializable {


    // Fields    

     private Long menuId;
     private Menu menu;
     private String menuName;
     private Long menuLevel;
     private String menuUrl;
     private String description;
     private String menuState;
     private Long menuOrder;
     private Set userProperties = new HashSet(0);
     private Set menus = new HashSet(0);


    // Constructors

    /** default constructor */
    public Menu() {
    }

	/** minimal constructor */
    public Menu(Long menuId, String menuName) {
        this.menuId = menuId;
        this.menuName = menuName;
    }
    
    /** full constructor */
    public Menu(Long menuId, Menu menu, String menuName, Long menuLevel, String menuUrl, String description, String menuState, Set menus) {
        this.menuId = menuId;
        this.menu = menu;
        this.menuName = menuName;
        this.menuLevel = menuLevel;
        this.menuUrl = menuUrl;
        this.description = description;
        this.menuState = menuState;
        this.menus = menus;
    }

   
    // Property accessors

    public Long getMenuId() {
        return this.menuId;
    }
    
    public void setMenuId(Long menuId) {
        this.menuId = menuId;
    }

    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }

    public String getMenuName() {
        return this.menuName;
    }
    
    public void setMenuName(String menuName) {
        this.menuName = menuName;
    }

    public Long getMenuLevel() {
        return this.menuLevel;
    }
    
    public void setMenuLevel(Long menuLevel) {
        this.menuLevel = menuLevel;
    }

    public String getMenuUrl() {
        return this.menuUrl;
    }
    
    public void setMenuUrl(String menuUrl) {
        this.menuUrl = menuUrl;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getMenuState() {
        return this.menuState;
    }
    
    public void setMenuState(String menuState) {
        this.menuState = menuState;
    }

    public Set getUserProperties() {
        return this.userProperties;
    }
    
    public void setUserProperties(Set userProperties) {
        this.userProperties = userProperties;
    }

    public Set getMenus() {
        return this.menus;
    }
    
    public void setMenus(Set menus) {
        this.menus = menus;
    }

	public Long getMenuOrder() {
		return menuOrder;
	}

	public void setMenuOrder(Long menuOrder) {
		this.menuOrder = menuOrder;
	}
   








}