package com.xwtech.mss.pub.po;

import java.util.HashSet;
import java.util.Set;

/**
 * MpmsBoardMsg generated by MyEclipse - Hibernate Tools
 */

public class MpmsBoardMsg  implements java.io.Serializable {


    // Fields    

     private Long msgId;
     private UserInfo userInfo;
     private String createTime;
     private String msgInfo;
     private String status;
//     private COrganizationNj ciOrganizationNj;
     private Set mpmsBoardMsgResps = new HashSet(0);


    // Constructors

    /** default constructor */
    public MpmsBoardMsg() {
    }

	/** minimal constructor */
    public MpmsBoardMsg(Long msgId, UserInfo userInfo, String createTime) {
        this.msgId = msgId;
        this.userInfo = userInfo;
        this.createTime = createTime;
    }
    
    /** full constructor */
    public MpmsBoardMsg(Long msgId, UserInfo userInfo, String createTime, String msgInfo, String status, Set mpmsBoardMsgResps) {
        this.msgId = msgId;
        this.userInfo = userInfo;
        this.createTime = createTime;
        this.msgInfo = msgInfo;
        this.status = status;
        this.mpmsBoardMsgResps = mpmsBoardMsgResps;
    }

   
    // Property accessors

    public Long getMsgId() {
        return this.msgId;
    }
    
    public void setMsgId(Long msgId) {
        this.msgId = msgId;
    }

    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }

    public String getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getMsgInfo() {
        return this.msgInfo;
    }
    
    public void setMsgInfo(String msgInfo) {
        this.msgInfo = msgInfo;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    public Set getMpmsBoardMsgResps() {
        return this.mpmsBoardMsgResps;
    }
    
    public void setMpmsBoardMsgResps(Set mpmsBoardMsgResps) {
        this.mpmsBoardMsgResps = mpmsBoardMsgResps;
    }

//	public COrganizationNj getCiOrganizationNj() {
//		return ciOrganizationNj;
//	}
//
//	public void setCiOrganizationNj(COrganizationNj ciOrganizationNj) {
//		this.ciOrganizationNj = ciOrganizationNj;
//	}
   








}