package com.xwtech.mss.pub.po;

import java.util.HashSet;
import java.util.Set;

/**
 * MpmsBoardMsg generated by MyEclipse - Hibernate Tools
 */

public class MpmsAuthorization  implements java.io.Serializable {


    // Fields    

     /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	private Long id;
     private String password;
     private String status;
     private String createTime;
     private String updateTime;


    // Constructors

    /** default constructor */
    public MpmsAuthorization() {
    }

	/** minimal constructor */
    public MpmsAuthorization(Long id, String password, String status,String createTime,String updateTime) {
        this.id = id;
        this.password = password;
        this.createTime = createTime;
        this.updateTime = updateTime;
        this.status = status;
    }
    
   
    // Property accessors

    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }

    public String getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

	public String getPassword() {
		return password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getUpdateTime() {
		return updateTime;
	}

	public void setUpdateTime(String updateTime) {
		this.updateTime = updateTime;
	}
}