package com.xwtech.mss.pub.po;



/**
 * MpmsBoardMsgResp generated by MyEclipse - Hibernate Tools
 */

public class MpmsBoardMsgResp  implements java.io.Serializable {


    // Fields    

     private Long respId;
     private MpmsBoardMsg mpmsBoardMsg;
     private Long mpmUserId;
     private String respInfo;
     private String respTime;
     private String status;


    // Constructors

    /** default constructor */
    public MpmsBoardMsgResp() {
    }

	/** minimal constructor */
    public MpmsBoardMsgResp(Long respId, MpmsBoardMsg mpmsBoardMsg, String respTime,String status) {
        this.respId = respId;
        this.mpmsBoardMsg = mpmsBoardMsg;
        this.respTime = respTime;
        this.status = status;
    }
    
    /** full constructor */
    public MpmsBoardMsgResp(Long respId, MpmsBoardMsg mpmsBoardMsg, Long mpmUserId, String respInfo, String respTime,String status) {
        this.respId = respId;
        this.mpmsBoardMsg = mpmsBoardMsg;
        this.mpmUserId = mpmUserId;
        this.respInfo = respInfo;
        this.respTime = respTime;
        this.status = status;
    }

   
    // Property accessors

    public Long getRespId() {
        return this.respId;
    }
    
    public void setRespId(Long respId) {
        this.respId = respId;
    }

    public MpmsBoardMsg getMpmsBoardMsg() {
        return this.mpmsBoardMsg;
    }
    
    public void setMpmsBoardMsg(MpmsBoardMsg mpmsBoardMsg) {
        this.mpmsBoardMsg = mpmsBoardMsg;
    }

    public Long getMpmUserId() {
        return this.mpmUserId;
    }
    
    public void setMpmUserId(Long mpmUserId) {
        this.mpmUserId = mpmUserId;
    }

    public String getRespInfo() {
        return this.respInfo;
    }
    
    public void setRespInfo(String respInfo) {
        this.respInfo = respInfo;
    }

    public String getRespTime() {
        return this.respTime;
    }
    
    public void setRespTime(String respTime) {
        this.respTime = respTime;
    }

	public String getStatus() {
		return status;
	}

	public void setStatus(String status) {
		this.status = status;
	}
   
}