package com.xwtech.mss.pub.po;

import java.util.HashSet;
import java.util.Set;


/**
 * FrameOrgnization generated by MyEclipse - Hibernate Tools
 */

public class Orgnization  implements java.io.Serializable {


    // Fields    

     private Long orgId;
     private Orgnization orgnization;
     private String orgName;
     private String description;
     private Long orgLevel;
     private String state;
     private Set userInfos = new HashSet(0);
     private Set orgnizations = new HashSet(0);
     private Set frameOrgCityRelations = new HashSet(0);

    // Constructors

    /** default constructor */
    public Orgnization() {
    }

	/** minimal constructor */
    public Orgnization(String orgName, String state) {
        this.orgName = orgName;
        this.state = state;
    }
    
    /** full constructor */
    public Orgnization(Orgnization orgnization, String orgName, String description, Long orgLevel, String state,Set frameOrgCityRelations, Set userInfos, Set orgnizations) {
        this.orgnization = orgnization;
        this.orgName = orgName;
        this.description = description;
        this.orgLevel = orgLevel;
        this.state = state;
        this.frameOrgCityRelations = frameOrgCityRelations;
        this.userInfos = userInfos;
        this.orgnizations = orgnizations;
    }

   
    // Property accessors

    public Long getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }

    public Orgnization getOrgnization() {
        return this.orgnization;
    }
    
    public void setOrgnization(Orgnization orgnization) {
        this.orgnization = orgnization;
    }

    public String getOrgName() {
        return this.orgName;
    }
    
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public Long getOrgLevel() {
        return this.orgLevel;
    }
    
    public void setOrgLevel(Long orgLevel) {
        this.orgLevel = orgLevel;
    }

    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }

    public Set getUserInfos() {
        return this.userInfos;
    }
    
    public void setUserInfos(Set userInfos) {
        this.userInfos = userInfos;
    }

    public Set getOrgnizations() {
        return this.orgnizations;
    }
    
    public void setOrgnizations(Set orgnizations) {
        this.orgnizations = orgnizations;
    }
   
    public Set getFrameOrgCityRelations() {
        return this.frameOrgCityRelations;
    }
    
    public void setFrameOrgCityRelations(Set frameOrgCityRelations) {
        this.frameOrgCityRelations = frameOrgCityRelations;
    }







}