package com.xwtech.mss.pub.po;

import java.util.HashSet;
import java.util.Set;



/**
 * MssRole generated by MyEclipse - Hibernate Tools
 */

public class Role  implements java.io.Serializable {


    // Fields    

     private Long roleId;
     private String roleName;
     private String description;
     private String state;
     private Set userProperties = new HashSet(0);
     private Set userInfos = new HashSet(0);
     private Set frameUrls = new HashSet(0);


    // Constructors

    /** default constructor */
    public Role() {
    }

	/** minimal constructor */
    public Role(Long roleId, String roleName, String state) {
        this.roleId = roleId;
        this.roleName = roleName;
        this.state = state;
    }
    
    /** full constructor */
    public Role(Long roleId, String roleName, String description, String state) {
        this.roleId = roleId;
        this.roleName = roleName;
        this.description = description;
        this.state = state;
    }

   
    // Property accessors

    public Long getRoleId() {
        return this.roleId;
    }
    
    public void setRoleId(Long roleId) {
        this.roleId = roleId;
    }

    public String getRoleName() {
        return this.roleName;
    }
    
    public void setRoleName(String roleName) {
        this.roleName = roleName;
    }

    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
    public Set getUserProperties() {
        return this.userProperties;
    }
    
    public void setUserProperties(Set userProperties) {
        this.userProperties = userProperties;
    }

    public Set getUserInfos() {
		return userInfos;
	}

	public void setUserInfos(Set userInfos) {
		this.userInfos = userInfos;
	}

	public Set getFrameUrls() {
        return this.frameUrls;
    }
    
    public void setFrameUrls(Set frameUrls) {
        this.frameUrls = frameUrls;
    }

}