package com.xwtech.mss.pub.po;

import java.util.HashSet;
import java.util.Set;

import com.xwtech.mss.pub.tools.CommonOperation;

/**
 * MssUserInfo generated by MyEclipse - Hibernate Tools
 */

public class UserInfo  implements java.io.Serializable {


    // Fields    

     private Long userId;
     private Orgnization orgnization;
     private Role role;
     private Long userNum;
     private String userName;
     private String loginName;
     private String loginPwd;
     private Long userType;
     private String fax;
     private String tel;
     private String userState;
     private String email;
     private String delFlag;
//     private Set mssAuditingContractsForApplyUser = new HashSet(0);
//     private Set ciUserInfos = new HashSet(0);
//     private Set mssExpenseAccounts = new HashSet(0);
//     private Set mssOrdersInfos = new HashSet(0);
//     private Set mssAuditingContractsForLinkMan = new HashSet(0);
//     private Set userProperties = new HashSet(0);
//     private Set mssReqInfos = new HashSet(0);
//     private Set mssReqMaterials = new HashSet(0);

     //合同审批单可导入标志
//     private String contrImportFlag;

     //费用报销单/商务合同记帐单可导入标志
//     private String payImportFlag;
     
    // Constructors

    /** default constructor */
    public UserInfo() {
    }

	/** minimal constructor */
    public UserInfo(Long userId, Long userNum, String loginName, String loginPwd, String userState, String email) {
        this.userId = userId;
        this.userNum = userNum;
        this.loginName = loginName;
        this.loginPwd = loginPwd;
        this.userState = userState;
        this.email = email;
    }
    
    /** full constructor */
    public UserInfo(Long userId, /*Department mssDepartment,*/ Long userNum,String userTel, String userName, String loginName, String loginPwd, Long userType, String fax, String userState, String email/*, Set mssAuditingContractsForApplyUser, Set mssAuditingContractsForLinkMan, Set userProperties*/) {
        this.userId = userId;
//        this.mssDepartment = mssDepartment;
        this.userNum = userNum;
        this.userName = userName;
        this.loginName = loginName;
        this.loginPwd = loginPwd;
        this.userType = userType;
        this.fax = fax;
        this.userState = userState;
        this.email = email;
//        this.mssAuditingContractsForApplyUser = mssAuditingContractsForApplyUser;
//        this.mssAuditingContractsForLinkMan = mssAuditingContractsForLinkMan;
//        this.userProperties = userProperties;
        this.tel = userTel;
    }

   
    // Property accessors

    public Long getUserId() {
        return this.userId;
    }
    
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public Long getUserNum() {
        return this.userNum;
    }
    
    public void setUserNum(Long userNum) {
        this.userNum = userNum;
    }

    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }

    public String getLoginName() {
        return this.loginName;
    }
    
    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public String getLoginPwd() {
        return this.loginPwd;
    }
    
    public void setLoginPwd(String loginPwd) {
        this.loginPwd = loginPwd;
    }

    public Long getUserType() {
        return this.userType;
    }
    
    public void setUserType(Long userType) {
        this.userType = userType;
    }

    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }

    public String getUserState() {
        return this.userState;
    }
    
    public void setUserState(String userState) {
        this.userState = userState;
    }

	public String getTel() {
		return tel;
	}

	public void setTel(String tel) {
		this.tel = tel;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Orgnization getOrgnization() {
		return orgnization;
	}

	public void setOrgnization(Orgnization orgnization) {
		this.orgnization = orgnization;
	}

	public Role getRole() {
		return role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	public String getDelFlag() {
		return delFlag;
	}

	public void setDelFlag(String delFlag) {
		this.delFlag = delFlag;
	}
	
}