package com.xwtech.mss.pub.po;



/**
 * MssUserProperty generated by MyEclipse - Hibernate Tools
 */

public class UserProperty  implements java.io.Serializable {


    // Fields    

     private Long propertyId;
//     private UserInfo userInfo;
     private Role role;
     private Menu menu;
     private String state;


    // Constructors

    /** default constructor */
    public UserProperty() {
    }

	/** minimal constructor */
    public UserProperty(Long propertyId,  Role role, String state) {
        this.propertyId = propertyId;
//        this.userInfo = userInfo;
        this.role = role;
        this.state = state;
    }
    
    /** full constructor */
    public UserProperty(Long propertyId,  Role role, Menu menu, String state) {
        this.propertyId = propertyId;
//        this.userInfo = userInfo;
        this.role = role;
        this.menu = menu;
        this.state = state;
    }

   
    // Property accessors

    public Long getPropertyId() {
        return this.propertyId;
    }
    
    public void setPropertyId(Long propertyId) {
        this.propertyId = propertyId;
    }

//    public UserInfo getUserInfo() {
//        return this.userInfo;
//    }
//    
//    public void setUserInfo(UserInfo userInfo) {
//        this.userInfo = userInfo;
//    }

    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }

    public Menu getMenu() {
        return this.menu;
    }
    
    public void setMenu(Menu menu) {
        this.menu = menu;
    }

    public String getState() {
        return this.state;
    }
    
    public void setState(String state) {
        this.state = state;
    }
   








}